### ISSUE TITLE
D3

### ISSUE THREAD

**Issue by rebeccabkane** [Group-3-Applied-Project-And-Thesis/Currency-Analyser#6]
D3 possibly not suitable for what we require - Chart JS more lightweight? @taraokelly

**Comment by rebeccabernie** [comment]
D3 possibly not suitable for what we require - Chart JS more lightweight? @taraokelly

**Comment by taraokelly** [comment]
Chart.js was all we needed for  the dynamic graph when combined with the reactivity of Vue.js. A plugin, [vue-chartjs](http://vue-chartjs.org/#/), makes this process even simpler. D3.js would have been unnecessarily sophisticated for what we required.
